language: node_js
sudo: false
node_js:
  - 4
  - 6

cache:
  directories:
    - node_modules

script:
  - npm test

deploy:
  provider: npm
  email: lutien02@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: lutien/postcss-extract-value
