language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 7

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run coverage

deploy:
  provider: npm
  email: lutien02@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: lutien/postcss-extract-value
